openapi: 3.0.3
info:
  title: Microservicio de Cuentas
  description: API para la gestion de cuentas.
  version: 1.0.0
servers:
  - url: http://localhost:8081/api/v1
paths:
  /cuentas:
    get:
      summary: Obtener todas las cuentas
      responses:
        '200':
          description: Lista de cuentas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cuenta'
    post:
      summary: Crear una nueva cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cuenta'
      responses:
        '201':
          description: Cuenta creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cuenta'

  /cuentas/{id}:
    get:
      summary: Obtener cuenta por ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la cuenta
          schema:
            type: integer
      responses:
        '200':
          description: Cuenta encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cuenta'
        '404':
          description: Cuenta no encontrada
    put:
      summary: Actualizar cuenta
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la cuenta
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cuenta'
      responses:
        '200':
          description: Cuenta actualizada exitosamente
        '404':
          description: Cuenta no encontrada
    delete:
      summary: Eliminar cuenta
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la cuenta
          schema:
            type: integer
      responses:
        '204':
          description: Cuenta eliminada exitosamente
        '404':
          description: Cuenta no encontrada

components:
  schemas:
    Cuenta:
      type: object
      properties:
        id:
          type: integer
          format: int64
        clienteId:
          type: integer
        saldo:
          type: number
          format: double
      required:
        - clienteId
        - saldo
