openapi: 3.0.3
info:
  title: Microservicio de Transacciones Bancarias
  description: API para la gestión de transacciones bancarias en el banco XYZ.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /transacciones/deposito:
    post:
      summary: Registrar un depósito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransaccionDeposito'
      responses:
        '201':
          description: Depósito registrado exitosamente
        '400':
          description: Error en la operación

  /transacciones/retiro:
    post:
      summary: Registrar un retiro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransaccionRetiro'
      responses:
        '201':
          description: Retiro registrado exitosamente
        '400':
          description: Error en la operación

  /transacciones/transferencia:
    post:
      summary: Registrar una transferencia
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransaccionTransferencia'
      responses:
        '201':
          description: Transferencia registrada exitosamente
        '400':
          description: Error en la operación (por ejemplo, cuenta de destino no válida o saldo insuficiente)

  /transacciones/historial:
    get:
      summary: Consultar historial de transacciones
      parameters:
        - name: cuentaId
          in: query
          required: true
          description: ID de la cuenta para la que se quiere consultar el historial
          schema:
            type: integer
      responses:
        '200':
          description: Lista de transacciones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransaccionHistorial'
        '404':
          description: Historial no encontrado para la cuenta indicada

components:
  schemas:
    TransaccionDeposito:
      type: object
      properties:
        cuentaId:
          type: integer
        monto:
          type: number
          format: double
        fecha:
          type: string
          format: date-time
      required:
        - cuentaId
        - monto
        - fecha

    TransaccionRetiro:
      type: object
      properties:
        cuentaId:
          type: integer
        monto:
          type: number
          format: double
        fecha:
          type: string
          format: date-time
      required:
        - cuentaId
        - monto
        - fecha

    TransaccionTransferencia:
      type: object
      properties:
        cuentaOrigenId:
          type: integer
        cuentaDestinoId:
          type: integer
        monto:
          type: number
          format: double
        fecha:
          type: string
          format: date-time
      required:
        - cuentaOrigenId
        - cuentaDestinoId
        - monto
        - fecha

    TransaccionHistorial:
      type: object
      properties:
        tipo:
          type: string
          enum: [DEPOSITO, RETIRO, TRANSFERENCIA]
        cuentaOrigenId:
          type: integer
        cuentaDestinoId:
          type: integer
        monto:
          type: number
          format: double
        fecha:
          type: string
          format: date-time
      required:
        - tipo
        - cuentaOrigenId
        - monto
        - fecha